image: git.dti.crosemont.quebec:5050/progression/publication:latest 

# Production de la documentation
.doc: &doc
  script:
  - mkdir public
  - bash publish.sh .
  - mv /tmp/public/* public/

tests:
  stage: test
  script:
  - find tests/ -type f -name info.yml -print -exec bash -c "python3 -m progression_qc {} >/dev/null" \;

pages:
  <<: *doc
  stage: publication
  artifacts:
    paths:
    - public

stages:
  - clone
  - test
  - publication
